include: switch to usb_bam.h from stock N
* Because here i've replaced whole usb folder with stock: https://github.com/skinzor/android_kernel_huawei_msm8953-2/commit/798fa9995f65c1f18f59d433a41e818df0fcd308
* And here i've replaced usb_bam.c with stock: https://github.com/skinzor/android_kernel_huawei_msm8953-2/commit/abb5e66052513e9833040f84ea2b0bd1b2fef0c1

* Obviously, i'll need to merge usb's stock code into CAF, but i'm just lazy now.

* It should also fix the following build error:

  CC      drivers/platform/msm/usb_bam.o
../../../../../../kernel/huawei/msm8953/drivers/platform/msm/usb_bam.c: In function 'usb_bam_dt_to_pdata':
../../../../../../kernel/huawei/msm8953/drivers/platform/msm/usb_bam.c:2889:7: error: 'struct msm_usb_bam_platform_data' has no member named 'enable_hsusb_bam_on_boot'
  pdata->enable_hsusb_bam_on_boot = of_property_read_bool(node,
       ^
../../../../../../kernel/huawei/msm8953/drivers/platform/msm/usb_bam.c: In function 'usb_bam_init':
../../../../../../kernel/huawei/msm8953/drivers/platform/msm/usb_bam.c:3053:11: error: 'struct msm_usb_bam_platform_data' has no member named 'enable_hsusb_bam_on_boot'
  if (pdata->enable_hsusb_bam_on_boot && bam_type == CI_CTRL) {
           ^
../../../../../../kernel/huawei/msm8953/drivers/platform/msm/usb_bam.c: In function 'msm_do_bam_disable_enable':
../../../../../../kernel/huawei/msm8953/drivers/platform/msm/usb_bam.c:3420:32: error: 'struct msm_usb_bam_platform_data' has no member named 'enable_hsusb_bam_on_boot'
  if ((bam != CI_CTRL) || !pdata->enable_hsusb_bam_on_boot)
                                ^
../../../../../../kernel/huawei/msm8953/drivers/platform/msm/usb_bam.c: In function 'msm_usb_bam_enable':
../../../../../../kernel/huawei/msm8953/drivers/platform/msm/usb_bam.c:3530:11: error: 'struct msm_usb_bam_platform_data' has no member named 'enable_hsusb_bam_on_boot'
      pdata->enable_hsusb_bam_on_boot))
           ^
make[5]: *** [/home/robert/Nova/LOS14/kernel/huawei/msm8953/scripts/Makefile.build:258: drivers/platform/msm/usb_bam.o] Error 1
make[4]: *** [/home/robert/Nova/LOS14/kernel/huawei/msm8953/scripts/Makefile.build:402: drivers/platform/msm] Error 2
make[3]: *** [/home/robert/Nova/LOS14/kernel/huawei/msm8953/scripts/Makefile.build:402: drivers/platform] Error 2
make[2]: *** [/home/robert/Nova/LOS14/kernel/huawei/msm8953/Makefile:955: drivers] Error 2
make[2]: Leaving directory '/home/robert/Nova/LOS14/out/target/product/hwcan/obj/KERNEL_OBJ'
make[1]: *** [Makefile:145: sub-make] Error 2
make[1]: Leaving directory '/home/robert/Nova/LOS14/kernel/huawei/msm8953'
make: *** [vendor/cm/build/tasks/kernel.mk:282: TARGET_KERNEL_BINARIES] Error 2